global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'carineland-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'vercel-metrics'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['carineland.fr']
    scheme: https
